export default {
  andromeeda: {
    name: "Andromeeda",
    dark: true,
    import: () => import("@shikijs/themes/andromeeda"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "aurora-x": {
    name: "Aurora X",
    dark: true,
    import: () => import("@shikijs/themes/aurora-x"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "ayu-dark": {
    name: "Ayu Dark",
    dark: true,
    import: () => import("@shikijs/themes/ayu-dark"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "ayu-mirage": {
    name: "Ayu Mirage",
    dark: true,
    import: () => import("@shikijs/themes/ayu-mirage"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "catppuccin-frappe": {
    name: "Catppuccin Frappé",
    dark: true,
    import: () => import("@shikijs/themes/catppuccin-frappe"),
    bracketColors: [
      "#e78284",
      "#ef9f76",
      "#e5c890",
      "#a6d189",
      "#85c1dc",
      "#ca9ee6",
      "#ea999c",
    ],
  },
  "catppuccin-macchiato": {
    name: "Catppuccin Macchiato",
    dark: true,
    import: () => import("@shikijs/themes/catppuccin-macchiato"),
    bracketColors: [
      "#ed8796",
      "#f5a97f",
      "#eed49f",
      "#a6da95",
      "#7dc4e4",
      "#c6a0f6",
      "#ee99a0",
    ],
  },
  "catppuccin-mocha": {
    name: "Catppuccin Mocha",
    dark: true,
    import: () => import("@shikijs/themes/catppuccin-mocha"),
    bracketColors: [
      "#f38ba8",
      "#fab387",
      "#f9e2af",
      "#a6e3a1",
      "#74c7ec",
      "#cba6f7",
      "#eba0ac",
    ],
  },
  "dark-plus": {
    name: "Dark Plus",
    dark: true,
    import: () => import("@shikijs/themes/dark-plus"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  dracula: {
    name: "Dracula Theme",
    dark: true,
    import: () => import("@shikijs/themes/dracula"),
    bracketColors: [
      "#F8F8F2",
      "#FF79C6",
      "#8BE9FD",
      "#50FA7B",
      "#BD93F9",
      "#FFB86C",
      "#FF5555",
    ],
  },
  "dracula-soft": {
    name: "Dracula Theme Soft",
    dark: true,
    import: () => import("@shikijs/themes/dracula-soft"),
    bracketColors: [
      "#f6f6f4",
      "#f286c4",
      "#97e1f1",
      "#62e884",
      "#bf9eee",
      "#FFB86C",
      "#ee6666",
    ],
  },
  "everforest-dark": {
    name: "Everforest Dark",
    dark: true,
    import: () => import("@shikijs/themes/everforest-dark"),
    bracketColors: [
      "#e67e80",
      "#dbbc7f",
      "#a7c080",
      "#7fbbb3",
      "#e69875",
      "#d699b6",
      "#859289",
    ],
  },
  "github-dark": {
    name: "GitHub Dark",
    dark: true,
    import: () => import("@shikijs/themes/github-dark"),
    bracketColors: [
      "#79b8ff",
      "#ffab70",
      "#b392f0",
      "#79b8ff",
      "#ffab70",
      "#b392f0",
      "rgba(255, 18, 18, 0.8)",
    ],
  },
  "github-dark-default": {
    name: "GitHub Dark Default",
    dark: true,
    import: () => import("@shikijs/themes/github-dark-default"),
    bracketColors: [
      "#79c0ff",
      "#56d364",
      "#e3b341",
      "#ffa198",
      "#ff9bce",
      "#d2a8ff",
      "#7d8590",
    ],
  },
  "github-dark-dimmed": {
    name: "GitHub Dark Dimmed",
    dark: true,
    import: () => import("@shikijs/themes/github-dark-dimmed"),
    bracketColors: [
      "#6cb6ff",
      "#6bc46d",
      "#daaa3f",
      "#ff938a",
      "#fc8dc7",
      "#dcbdfb",
      "#768390",
    ],
  },
  "github-dark-high-contrast": {
    name: "GitHub Dark High Contrast",
    dark: true,
    import: () => import("@shikijs/themes/github-dark-high-contrast"),
    bracketColors: [
      "#91cbff",
      "#4ae168",
      "#f7c843",
      "#ffb1af",
      "#ffadd4",
      "#dbb7ff",
      "#f0f3f6",
    ],
  },
  "gruvbox-dark-hard": {
    name: "Gruvbox Dark Hard",
    dark: true,
    import: () => import("@shikijs/themes/gruvbox-dark-hard"),
    bracketColors: [
      "#b16286",
      "#458588",
      "#689d6a",
      "#98971a",
      "#d79921",
      "#d65d0e",
      "#cc241d",
    ],
  },
  "gruvbox-dark-medium": {
    name: "Gruvbox Dark Medium",
    dark: true,
    import: () => import("@shikijs/themes/gruvbox-dark-medium"),
    bracketColors: [
      "#b16286",
      "#458588",
      "#689d6a",
      "#98971a",
      "#d79921",
      "#d65d0e",
      "#cc241d",
    ],
  },
  "gruvbox-dark-soft": {
    name: "Gruvbox Dark Soft",
    dark: true,
    import: () => import("@shikijs/themes/gruvbox-dark-soft"),
    bracketColors: [
      "#b16286",
      "#458588",
      "#689d6a",
      "#98971a",
      "#d79921",
      "#d65d0e",
      "#cc241d",
    ],
  },
  horizon: {
    name: "Horizon",
    dark: true,
    import: () => import("@shikijs/themes/horizon"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  houston: {
    name: "Houston",
    dark: true,
    import: () => import("@shikijs/themes/houston"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "kanagawa-dragon": {
    name: "Kanagawa Dragon",
    dark: true,
    import: () => import("@shikijs/themes/kanagawa-dragon"),
    bracketColors: [
      "#8992A7",
      "#B6927B",
      "#8BA4B0",
      "#A292A3",
      "#C4B28A",
      "#8EA4A2",
      "#C4746E",
    ],
  },
  "kanagawa-wave": {
    name: "Kanagawa Wave",
    dark: true,
    import: () => import("@shikijs/themes/kanagawa-wave"),
    bracketColors: [
      "#957FB8",
      "#FFA066",
      "#7E9CD8",
      "#D27E99",
      "#E6C384",
      "#7AA89F",
      "#FF5D62",
    ],
  },
  laserwave: {
    name: "LaserWave",
    dark: true,
    import: () => import("@shikijs/themes/laserwave"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "material-theme": {
    name: "Material Theme",
    dark: true,
    import: () => import("@shikijs/themes/material-theme"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "material-theme-darker": {
    name: "Material Theme Darker",
    dark: true,
    import: () => import("@shikijs/themes/material-theme-darker"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "material-theme-ocean": {
    name: "Material Theme Ocean",
    dark: true,
    import: () => import("@shikijs/themes/material-theme-ocean"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "material-theme-palenight": {
    name: "Material Theme Palenight",
    dark: true,
    import: () => import("@shikijs/themes/material-theme-palenight"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "min-dark": {
    name: "Min Dark",
    dark: true,
    import: () => import("@shikijs/themes/min-dark"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  monokai: {
    name: "Monokai",
    dark: true,
    import: () => import("@shikijs/themes/monokai"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "night-owl": {
    name: "Night Owl",
    dark: true,
    import: () => import("@shikijs/themes/night-owl"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  nord: {
    name: "Nord",
    dark: true,
    import: () => import("@shikijs/themes/nord"),
    bracketColors: [
      "#8fbcbb",
      "#88c0d0",
      "#81a1c1",
      "#5e81ac",
      "#8fbcbb",
      "#88c0d0",
      "#bf616a",
    ],
  },
  "one-dark-pro": {
    name: "One Dark Pro",
    dark: true,
    import: () => import("@shikijs/themes/one-dark-pro"),
    bracketColors: ["#d19a66", "#c678dd", "#56b6c2", "rgba(255, 18, 18, 0.8)"],
  },
  plastic: {
    name: "Plastic",
    dark: true,
    import: () => import("@shikijs/themes/plastic"),
    bracketColors: [
      "#A9B2C3",
      "#61AFEF",
      "#E5C07B",
      "#E06C75",
      "#98C379",
      "#B57EDC",
      "#D74E42",
    ],
  },
  poimandres: {
    name: "Poimandres",
    dark: true,
    import: () => import("@shikijs/themes/poimandres"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  red: {
    name: "Red",
    dark: true,
    import: () => import("@shikijs/themes/red"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "rose-pine": {
    name: "Rosé Pine",
    dark: true,
    import: () => import("@shikijs/themes/rose-pine"),
    bracketColors: [
      "#eb6f9280",
      "#31748f80",
      "#f6c17780",
      "#9ccfd880",
      "#ebbcba80",
      "#c4a7e780",
      "rgba(255, 18, 18, 0.8)",
    ],
  },
  "rose-pine-moon": {
    name: "Rosé Pine Moon",
    dark: true,
    import: () => import("@shikijs/themes/rose-pine-moon"),
    bracketColors: [
      "#eb6f9280",
      "#3e8fb080",
      "#f6c17780",
      "#9ccfd880",
      "#ea9a9780",
      "#c4a7e780",
      "rgba(255, 18, 18, 0.8)",
    ],
  },
  "slack-dark": {
    name: "Slack Dark",
    dark: true,
    import: () => import("@shikijs/themes/slack-dark"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "solarized-dark": {
    name: "Solarized Dark",
    dark: true,
    import: () => import("@shikijs/themes/solarized-dark"),
    bracketColors: [
      "#cdcdcdff",
      "#b58900ff",
      "#d33682ff",
      "rgba(255, 18, 18, 0.8)",
    ],
  },
  "synthwave-84": {
    name: "Synthwave '84",
    dark: true,
    import: () => import("@shikijs/themes/synthwave-84"),
    bracketColors: ["#FFD700", "#DA70D6", "#179FFF", "rgba(255, 18, 18, 0.8)"],
  },
  "tokyo-night": {
    name: "Tokyo Night",
    dark: true,
    import: () => import("@shikijs/themes/tokyo-night"),
    bracketColors: [
      "#698cd6",
      "#68b3de",
      "#9a7ecc",
      "#25aac2",
      "#80a856",
      "#c49a5a",
      "#db4b4b",
    ],
  },
  vesper: {
    name: "Vesper",
    dark: true,
    import: () => import("@shikijs/themes/vesper"),
    bracketColors: [
      "#A0A0A0",
      "#A0A0A0",
      "#A0A0A0",
      "#A0A0A0",
      "#A0A0A0",
      "#A0A0A0",
      "#FF8080",
    ],
  },
  "vitesse-black": {
    name: "Vitesse Black",
    dark: true,
    import: () => import("@shikijs/themes/vitesse-black"),
    bracketColors: [
      "#5eaab5",
      "#4d9375",
      "#d4976c",
      "#d9739f",
      "#e6cc77",
      "#6394bf",
      "rgba(255, 18, 18, 0.8)",
    ],
  },
  "vitesse-dark": {
    name: "Vitesse Dark",
    dark: true,
    import: () => import("@shikijs/themes/vitesse-dark"),
    bracketColors: [
      "#5eaab5",
      "#4d9375",
      "#d4976c",
      "#d9739f",
      "#e6cc77",
      "#6394bf",
      "rgba(255, 18, 18, 0.8)",
    ],
  },
  "ayu-light": {
    name: "Ayu Light",
    dark: false,
    import: () => import("@shikijs/themes/ayu-light"),
    bracketColors: ["#0431FA", "#319331", "#7B3814", "rgba(255, 18, 18, 0.8)"],
  },
  "catppuccin-latte": {
    name: "Catppuccin Latte",
    dark: false,
    import: () => import("@shikijs/themes/catppuccin-latte"),
    bracketColors: [
      "#d20f39",
      "#fe640b",
      "#df8e1d",
      "#40a02b",
      "#209fb5",
      "#8839ef",
      "#e64553",
    ],
  },
  "everforest-light": {
    name: "Everforest Light",
    dark: false,
    import: () => import("@shikijs/themes/everforest-light"),
    bracketColors: [
      "#f85552",
      "#dfa000",
      "#8da101",
      "#3a94c5",
      "#f57d26",
      "#df69ba",
      "#939f91",
    ],
  },
  "github-light": {
    name: "GitHub Light",
    dark: false,
    import: () => import("@shikijs/themes/github-light"),
    bracketColors: [
      "#005cc5",
      "#e36209",
      "#5a32a3",
      "#005cc5",
      "#e36209",
      "#5a32a3",
      "rgba(255, 18, 18, 0.8)",
    ],
  },
  "github-light-default": {
    name: "GitHub Light Default",
    dark: false,
    import: () => import("@shikijs/themes/github-light-default"),
    bracketColors: [
      "#0969da",
      "#1a7f37",
      "#9a6700",
      "#cf222e",
      "#bf3989",
      "#8250df",
      "#656d76",
    ],
  },
  "github-light-high-contrast": {
    name: "GitHub Light High Contrast",
    dark: false,
    import: () => import("@shikijs/themes/github-light-high-contrast"),
    bracketColors: [
      "#0349b4",
      "#055d20",
      "#744500",
      "#a0111f",
      "#971368",
      "#622cbc",
      "#0e1116",
    ],
  },
  "gruvbox-light-hard": {
    name: "Gruvbox Light Hard",
    dark: false,
    import: () => import("@shikijs/themes/gruvbox-light-hard"),
    bracketColors: [
      "#b16286",
      "#458588",
      "#689d6a",
      "#98971a",
      "#d79921",
      "#d65d0e",
      "#cc241d",
    ],
  },
  "gruvbox-light-medium": {
    name: "Gruvbox Light Medium",
    dark: false,
    import: () => import("@shikijs/themes/gruvbox-light-medium"),
    bracketColors: [
      "#b16286",
      "#458588",
      "#689d6a",
      "#98971a",
      "#d79921",
      "#d65d0e",
      "#cc241d",
    ],
  },
  "gruvbox-light-soft": {
    name: "Gruvbox Light Soft",
    dark: false,
    import: () => import("@shikijs/themes/gruvbox-light-soft"),
    bracketColors: [
      "#b16286",
      "#458588",
      "#689d6a",
      "#98971a",
      "#d79921",
      "#d65d0e",
      "#cc241d",
    ],
  },
  "horizon-bright": {
    name: "Horizon Bright",
    dark: false,
    import: () => import("@shikijs/themes/horizon-bright"),
    bracketColors: ["#0431FA", "#319331", "#7B3814", "rgba(255, 18, 18, 0.8)"],
  },
  "kanagawa-lotus": {
    name: "Kanagawa Lotus",
    dark: false,
    import: () => import("@shikijs/themes/kanagawa-lotus"),
    bracketColors: [
      "#624C83",
      "#CC6D00",
      "#4D699B",
      "#B35B79",
      "#77713F",
      "#597B75",
      "#D9A594",
    ],
  },
  "light-plus": {
    name: "Light Plus",
    dark: false,
    import: () => import("@shikijs/themes/light-plus"),
    bracketColors: ["#0431FA", "#319331", "#7B3814", "rgba(255, 18, 18, 0.8)"],
  },
  "material-theme-lighter": {
    name: "Material Theme Lighter",
    dark: false,
    import: () => import("@shikijs/themes/material-theme-lighter"),
    bracketColors: ["#0431FA", "#319331", "#7B3814", "rgba(255, 18, 18, 0.8)"],
  },
  "min-light": {
    name: "Min Light",
    dark: false,
    import: () => import("@shikijs/themes/min-light"),
    bracketColors: ["#0431FA", "#319331", "#7B3814", "rgba(255, 18, 18, 0.8)"],
  },
  "night-owl-light": {
    name: "Night Owl Light",
    dark: false,
    import: () => import("@shikijs/themes/night-owl-light"),
    bracketColors: ["#0431FA", "#319331", "#7B3814", "rgba(255, 18, 18, 0.8)"],
  },
  "one-light": {
    name: "One Light",
    dark: false,
    import: () => import("@shikijs/themes/one-light"),
    bracketColors: ["#0431FA", "#319331", "#7B3814", "rgba(255, 18, 18, 0.8)"],
  },
  "rose-pine-dawn": {
    name: "Rosé Pine Dawn",
    dark: false,
    import: () => import("@shikijs/themes/rose-pine-dawn"),
    bracketColors: [
      "#b4637a80",
      "#28698380",
      "#ea9d3480",
      "#56949f80",
      "#d7827e80",
      "#907aa980",
      "rgba(255, 18, 18, 0.8)",
    ],
  },
  "slack-ochin": {
    name: "Slack Ochin",
    dark: false,
    import: () => import("@shikijs/themes/slack-ochin"),
    bracketColors: ["#0431FA", "#319331", "#7B3814", "rgba(255, 18, 18, 0.8)"],
  },
  "snazzy-light": {
    name: "Snazzy Light",
    dark: false,
    import: () => import("@shikijs/themes/snazzy-light"),
    bracketColors: ["#0431FA", "#319331", "#7B3814", "rgba(255, 18, 18, 0.8)"],
  },
  "solarized-light": {
    name: "Solarized Light",
    dark: false,
    import: () => import("@shikijs/themes/solarized-light"),
    bracketColors: ["#0431FA", "#319331", "#7B3814", "rgba(255, 18, 18, 0.8)"],
  },
  "vitesse-light": {
    name: "Vitesse Light",
    dark: false,
    import: () => import("@shikijs/themes/vitesse-light"),
    bracketColors: [
      "#2993a3",
      "#1e754f",
      "#a65e2b",
      "#a13865",
      "#bda437",
      "#296aa3",
      "rgba(255, 18, 18, 0.8)",
    ],
  },
} as const;
